// <auto-generated />
using Cyclix.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyclix.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230617141805_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Cyclix.Models.CycleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CycleBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Trek"
                        },
                        new
                        {
                            Id = 2,
                            name = "BMC"
                        },
                        new
                        {
                            Id = 3,
                            name = "Scott"
                        });
                });

            modelBuilder.Entity("Cyclix.Models.CycleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CycleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Rennvelo"
                        },
                        new
                        {
                            Id = 2,
                            name = "Reisevelo"
                        },
                        new
                        {
                            Id = 3,
                            name = "Elektro Velo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
